# TimeControl by Alex_qp
# By using this plugin you can control the daycycle of minecraft.

# Set this to true if you are finished with configuration. Then restart your server.
# Note: After restarting the plugin will proceed to disable gamerule doDaylightCycle of all worlds which where not disabled down below.
configured: false

# Set the delay between to time updates in ticks.
check-delay: 5

# Set to false if time in empty worlds should proceed.
deactivate_empty_worlds: true

# If no other values are set correctly in the worldConfiguration.yml for a enabled world these values will be applied for this world.
# For 99% of people the minecraft-... options are completely irrelevant. If you want to in- or decrease day or night, just edit day-length and night-length.
# For more information please visit the plugin's wiki at https://github.com/Alex39099/TimeControl/wiki
default_world_settings:
  minecraft-day-start-tick: 0
  minecraft-day-length: 12000
  day-length: 24000
  night-length: 7000
  needed-sleep-percentage: 0.5
  sleeping-night-time-multiplier: 20
  sleeping-storm-time-multiplier: 60

# Disable certain worlds by name or environment.
world_exceptions:
  by_name:
    # - world
    # - world_nether
    # - world_the_end
  by_environment:
    normal: false
    nether: true
    the_end: true
    custom: true

# Set to true if you want players in the specific gamemode to be counted as sleeping.
gamemode_sleeping:
  adventure: false
  creative: true
  spectator: true
  survival: false

# If set to true and Essentials flags a player as afk he will count as sleeping. You obviously have to install Essentials aka. EssentialsX in order for this to work. https://github.com/EssentialsX/Essentials/releases
essentials:
  afk_is_sleeping: false

messages:
  cmd:
    # This is the prefix of all command message outputs. An empty string will result in the default prefix.
    prefix: ""
    credits: "Use /timecontrol help for all available commands."
    help_header: "List of all available commands:"
    noPerm: "&4You do not have permission."
    wrongCmdUsagePrefix: "&CUsage:"

  # Messages regarding the sleeping mechanics.
  # Available placeholders:
  ## %sleep_needed% - Amount of needed sleeping players. (not available for sleeping.actionBar.msg.success)
  ## %sleep_sleeping% - Amount of actual sleeping players. (not sleeping ignored in any way) (not available for sleeping.actionBar.msg.success)
  ## %player% - the player's displayed name. (only available in sleeping.chat.msg)
  sleeping:
    actionBar:
      enable: true
      msg:
        success: "&eSweet dreams everyone!"
        progress: "&e%sleep_sleeping% of %sleep_needed% players are sleeping."
    chat:
      enable: true
      msg:
        enterBed: "%player% is now sleeping. (%sleep_sleeping%/%sleep_needed%)"
        leaveBed: "%player% left bed. (%sleep_sleeping%/%sleep_needed%)"

# Options regarding the updateChecker (by mfnalex (https://github.com/JEFF-Media-GbR/Spigot-UpdateChecker))
updatechecker:
  enable: true
  notify_op_on_login: true