main: com.github.alexqp.timecontrol.main.TimeControl
name: ${project.parent.name}
version: ${project.parent.version}
author: alexqp
description: ${project.parent.description}
api-version: "1.16"
depend: [ProtocolLib]
softdepend: [Essentials]
website: ${project.parent.url}

commands:
  timecontrol:
    description: All commands
    aliases: [tc]

permissions:
  timecontrol.*:
    description: Gives access to all TimeControl commands (except uninstall).
    default: false
    children:
      timecontrol.reload: true
      timecontrol.debug: true
      timecontrol.set: true
      timecontrol.set.*: true

  timecontrol.reload:
    description: Allows you to reload the plugin.
    default: op

  timecontrol.debug:
    description: Allows you to use the debug command.
    default: op

  timecontrol.set:
    description: Allows to change values.
    default: op

  timecontrol.set.*:
    description: Gives access to all commands for specific value changes.
    default: false
    children:
      timecontrol.set.mcdaylength: true
      timecontrol.set.mcdaystart: true
      timecontrol.set.daylength: true
      timecontrol.set.nightlength: true
      timecontrol.set.neededsleeppercentage: true
      timecontrol.set.sleepingnighttimemultiplier: true
      timecontrol.set.sleepingstormtimemultiplier: true

  timecontrol.set.mcdaylength:
    description: Allows to set the specific value minecraft-day-length
    default: op
  timecontrol.set.mcdaystart:
    description: Allows to set the specific value minecraft-day-start-tick
    default: op
  timecontrol.set.daylength:
    description: Allows to set the specific value day-length
    default: op
  timecontrol.set.nightlength:
    description: Allows to set the specific value night-length
    default: op
  timecontrol.set.neededsleeppercentage:
    description: Allows to set the specific value needed-sleep-percentage
    default: op
  timecontrol.set.sleepingnighttimemultiplier:
    description: Allows to set the specific value sleeping-time-multiplier
    default: op
  timecontrol.set.sleepingstormtimemultiplier:
    description: Allows to set the specific value storm-time-subtrahend
    default: op

  timecontrol.sleepingignored:
    description: Allows to be always counted as sleeping player (only in affected worlds).
    default: false

  timecontrol.sleep.actionbar:
    description: Allows to be notified by sleeping players via actionbar.
    default: true

  timecontrol.sleep.chat:
    description: Allows to be notified by sleeping players via chat.
    default: true